server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:8080/test?useUnicode=true&characterEncoding=utf-8&failOverReadOnly=false&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver